package za.ac.cput.stdregfrontend;

import javafx.fxml.FXML;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.DatePicker;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import za.ac.cput.domain.Address;
import za.ac.cput.domain.ContactDetails;
import za.ac.cput.domain.Gender;
import za.ac.cput.domain.Race;
import za.ac.cput.domain.Student;
import za.ac.cput.service.StudentService;

public class EditStudentController {

    @FXML
    private TextField firstNameField;

    @FXML
    private TextField lastNameField;

    @FXML
    private DatePicker dateOfBirthPicker;

    @FXML
    private TextField genderField;

    @FXML
    private TextField raceField;

    @FXML
    private TextField studentNumberField;

    @FXML
    private TextField studentEmailField;

    @FXML
    private TextField phoneNumberField;

    @FXML
    private TextField contactEmailField;

    @FXML
    private TextField streetField;

    @FXML
    private TextField suburbField;

    @FXML
    private TextField cityField;

    @FXML
    private TextField provinceField;

    @FXML
    private TextField postalCodeField;

    @FXML
    private Button saveButton;

    @FXML
    private Button cancelButton;

    private final StudentService studentService =
            new StudentService();

    private Student student;


    // ============================================================
    // RECEIVE STUDENT
    // ============================================================

    public void setStudent(Student student) {

        this.student = student;

        if (student == null) {

            showError(
                    "Edit Student",
                    "Student information could not be loaded."
            );

            return;
        }

        loadStudentInformation();
    }


    // ============================================================
    // LOAD STUDENT INFORMATION
    // ============================================================

    private void loadStudentInformation() {

        firstNameField.setText(
                safe(student.getFirstName())
        );

        lastNameField.setText(
                safe(student.getLastName())
        );

        dateOfBirthPicker.setValue(
                student.getDateOfBirth()
        );

        if (student.getGender() != null) {

            genderField.setText(
                    student.getGender().toString()
            );
        } else {

            genderField.clear();
        }

        if (student.getRace() != null) {

            raceField.setText(
                    student.getRace().toString()
            );
        } else {

            raceField.clear();
        }

        // --------------------------------------------------------
        // Generated student information
        // --------------------------------------------------------

        studentNumberField.setText(
                safe(student.getStudentNumber())
        );

        studentEmailField.setText(
                safe(student.getStudentEmail())
        );

        // These are generated by the backend.
        studentNumberField.setEditable(false);
        studentEmailField.setEditable(false);

        // --------------------------------------------------------
        // Contact Details
        // --------------------------------------------------------

        if (student.getContactDetails() != null) {

            ContactDetails contactDetails =
                    student.getContactDetails();

            contactEmailField.setText(
                    safe(contactDetails.getEmail())
            );

            phoneNumberField.setText(
                    safe(contactDetails.getPhoneNumber())
            );

        } else {

            contactEmailField.clear();
            phoneNumberField.clear();
        }

        // --------------------------------------------------------
        // Address
        // --------------------------------------------------------

        if (student.getAddress() != null) {

            Address address =
                    student.getAddress();

            streetField.setText(
                    safe(address.getStreet())
            );

            suburbField.setText(
                    safe(address.getSuburb())
            );

            cityField.setText(
                    safe(address.getCity())
            );

            provinceField.setText(
                    safe(address.getProvince())
            );

            postalCodeField.setText(
                    safe(address.getPostalCode())
            );

        } else {

            streetField.clear();
            suburbField.clear();
            cityField.clear();
            provinceField.clear();
            postalCodeField.clear();
        }
    }


    // ============================================================
    // SAVE CHANGES
    // ============================================================

    @FXML
    private void onSaveClick() {

        if (student == null) {

            showError(
                    "Edit Student",
                    "No student has been loaded."
            );

            return;
        }

        if (!validateForm()) {
            return;
        }

        try {

            // ----------------------------------------------------
            // Update Person information
            // ----------------------------------------------------

            student.setFirstName(
                    firstNameField.getText().trim()
            );

            student.setLastName(
                    lastNameField.getText().trim()
            );

            student.setDateOfBirth(
                    dateOfBirthPicker.getValue()
            );


            // ----------------------------------------------------
            // Update Gender
            // ----------------------------------------------------

            String genderText =
                    genderField.getText() == null
                            ? ""
                            : genderField
                            .getText()
                            .trim();

            if (!genderText.isEmpty()) {

                try {

                    student.setGender(
                            Gender.valueOf(
                                    genderText.toUpperCase()
                            )
                    );

                } catch (IllegalArgumentException e) {

                    showError(
                            "Invalid Gender",
                            "Please enter a valid gender.\n\n"
                                    + "Value entered: "
                                    + genderText
                    );

                    return;
                }

            } else {

                student.setGender(null);
            }


            // ----------------------------------------------------
            // Update Race
            // ----------------------------------------------------

            String raceText =
                    raceField.getText() == null
                            ? ""
                            : raceField
                            .getText()
                            .trim();

            if (!raceText.isEmpty()) {

                try {

                    student.setRace(
                            Race.valueOf(
                                    raceText.toUpperCase()
                            )
                    );

                } catch (IllegalArgumentException e) {

                    showError(
                            "Invalid Race",
                            "Please enter a valid race.\n\n"
                                    + "Value entered: "
                                    + raceText
                    );

                    return;
                }

            } else {

                student.setRace(null);
            }


            // ----------------------------------------------------
            // Update Contact Details
            // ----------------------------------------------------
            //
            // ContactDetails has no setters in the existing
            // frontend domain model.
            //
            // Therefore we create a new ContactDetails object
            // using the existing contact ID.
            // ----------------------------------------------------

            int contactId = 0;

            if (student.getContactDetails() != null) {

                contactId =
                        student.getContactDetails()
                                .getContactId();
            }

            String contactEmail =
                    contactEmailField.getText() == null
                            ? ""
                            : contactEmailField
                            .getText()
                            .trim();

            String phoneNumber =
                    phoneNumberField.getText() == null
                            ? ""
                            : phoneNumberField
                            .getText()
                            .trim();

            ContactDetails updatedContactDetails =
                    new ContactDetails(
                            contactId,
                            contactEmail,
                            phoneNumber
                    );

            student.setContactDetails(
                    updatedContactDetails
            );


            // ----------------------------------------------------
            // Update Address
            // ----------------------------------------------------
            //
            // Address also has no setters in the existing
            // frontend domain model.
            //
            // Therefore we create a new Address object using
            // the existing address ID.
            // ----------------------------------------------------

            int addressId = 0;

            if (student.getAddress() != null) {

                addressId =
                        student.getAddress()
                                .getAddressId();
            }

            String street =
                    streetField.getText() == null
                            ? ""
                            : streetField
                            .getText()
                            .trim();

            String suburb =
                    suburbField.getText() == null
                            ? ""
                            : suburbField
                            .getText()
                            .trim();

            String city =
                    cityField.getText() == null
                            ? ""
                            : cityField
                            .getText()
                            .trim();

            String province =
                    provinceField.getText() == null
                            ? ""
                            : provinceField
                            .getText()
                            .trim();

            String postalCode =
                    postalCodeField.getText() == null
                            ? ""
                            : postalCodeField
                            .getText()
                            .trim();

            Address updatedAddress =
                    new Address(
                            addressId,
                            street,
                            suburb,
                            city,
                            postalCode,
                            province
                    );

            student.setAddress(
                    updatedAddress
            );


            // ----------------------------------------------------
            // Send update to backend
            // ----------------------------------------------------

            Student updatedStudent =
                    studentService.update(student);

            if (updatedStudent == null) {

                showError(
                        "Update Student",
                        "The student could not be found."
                );

                return;
            }


            // ----------------------------------------------------
            // Success
            // ----------------------------------------------------

            showInformation(
                    "Update Student",
                    "Student information updated successfully."
            );

            closeWindow();

        } catch (Exception e) {

            e.printStackTrace();

            showError(
                    "Update Student Error",
                    getFullErrorMessage(e)
            );
        }
    }


    // ============================================================
    // VALIDATION
    // ============================================================

    private boolean validateForm() {

        if (firstNameField.getText() == null
                || firstNameField.getText().trim().isEmpty()) {

            showError(
                    "Validation Error",
                    "First name is required."
            );

            return false;
        }

        if (lastNameField.getText() == null
                || lastNameField.getText().trim().isEmpty()) {

            showError(
                    "Validation Error",
                    "Last name is required."
            );

            return false;
        }

        if (dateOfBirthPicker.getValue() == null) {

            showError(
                    "Validation Error",
                    "Date of birth is required."
            );

            return false;
        }

        return true;
    }


    // ============================================================
    // CANCEL
    // ============================================================

    @FXML
    private void onCancelClick() {

        closeWindow();
    }


    // ============================================================
    // CLOSE WINDOW
    // ============================================================

    private void closeWindow() {

        if (cancelButton != null
                && cancelButton.getScene() != null) {

            Stage stage =
                    (Stage) cancelButton
                            .getScene()
                            .getWindow();

            stage.close();

            return;
        }

        if (saveButton != null
                && saveButton.getScene() != null) {

            Stage stage =
                    (Stage) saveButton
                            .getScene()
                            .getWindow();

            stage.close();
        }
    }


    // ============================================================
    // SAFE STRING
    // ============================================================

    private String safe(String value) {

        if (value == null
                || value.trim().isEmpty()) {

            return "";
        }

        return value;
    }


    // ============================================================
    // INFORMATION ALERT
    // ============================================================

    private void showInformation(
            String title,
            String message
    ) {

        Alert alert =
                new Alert(
                        Alert.AlertType.INFORMATION
                );

        alert.setTitle(title);

        alert.setHeaderText(null);

        alert.setContentText(message);

        alert.showAndWait();
    }


    // ============================================================
    // ERROR ALERT
    // ============================================================

    private void showError(
            String title,
            String message
    ) {

        Alert alert =
                new Alert(
                        Alert.AlertType.ERROR
                );

        alert.setTitle(title);

        alert.setHeaderText(null);

        alert.setContentText(message);

        alert.showAndWait();
    }


    // ============================================================
    // COMPLETE ERROR MESSAGE
    // ============================================================

    private String getFullErrorMessage(
            Throwable e
    ) {

        StringBuilder message =
                new StringBuilder();

        Throwable current =
                e;

        while (current != null) {

            message.append(
                    current.getClass()
                            .getSimpleName()
            );

            if (current.getMessage() != null) {

                message.append(": ")
                        .append(current.getMessage());
            }

            message.append("\n\n");

            current =
                    current.getCause();
        }

        return message.toString();
    }
}